/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-11-08 09:18:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/oracle%202/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CollabPortal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1472200809268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Majestic Login Form Widget Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/*--A Design by W3layouts \r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("--*/\r\n");
      out.write("/*--- reset code ---*/\r\n");
      out.write("html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,dl,dt,dd,ol,nav ul,nav li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video {\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tborder:0;\r\n");
      out.write("\tfont-size:100%;\r\n");
      out.write("\tfont:inherit;\r\n");
      out.write("\tvertical-align:baseline;\r\n");
      out.write("}\r\n");
      out.write("article, aside, details, figcaption, figure,footer, header, hgroup, menu, nav, section {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("ol,ul {\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("}\r\n");
      out.write("blockquote,q {\r\n");
      out.write("\tquotes:none;\r\n");
      out.write("}\r\n");
      out.write("blockquote:before,blockquote:after,q:before,q:after {\r\n");
      out.write("\tcontent:'';\r\n");
      out.write("\tcontent:none;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("\tborder-spacing:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* start editing from here */\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".txt-rt {\r\n");
      out.write("\ttext-align:right;\r\n");
      out.write("}/* text align right */\r\n");
      out.write(".txt-lt {\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}/* text align left */\r\n");
      out.write(".txt-center {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("/*-- W3Layouts --*/\t\r\n");
      out.write("}/* text align center */\r\n");
      out.write(".float-rt {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("}/* float right */\r\n");
      out.write(".float-lt {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}/* float left */\r\n");
      out.write(".clear {\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}/* clear float */\r\n");
      out.write(".pos-relative {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("}/* Position Relative */\r\n");
      out.write(".pos-absolute {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("}/* Position Absolute */\r\n");
      out.write(".vertical-base {\t\r\n");
      out.write("\tvertical-align:baseline;\r\n");
      out.write("}/* vertical align baseline */\r\n");
      out.write(".vertical-top {\t\r\n");
      out.write("\tvertical-align:top;\r\n");
      out.write("}/* vertical align top */\r\n");
      out.write("nav.vertical ul li {\t\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("}/* vertical menu */\r\n");
      out.write("nav.horizontal ul li {\t\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}/* horizontal menu */\r\n");
      out.write("img {\r\n");
      out.write("\tmax-width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*--- end reset code ---*/\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground:url(resources/images/wooden.jpg);\r\n");
      out.write("\tbackground-repeat:no-repeat;\r\n");
      out.write("\tbackground-position:center;\r\n");
      out.write("\tbackground-attachment:fixed;\r\n");
      out.write("\tbackground-size:100% 100%;\r\n");
      out.write("\t-webkit-background-size:100% 100%;\r\n");
      out.write("\t-moz-background-size:100% 100%;\r\n");
      out.write("\t-o-background-size:100% 100%;\r\n");
      out.write("\t-ms-background-size:100% 100%;\r\n");
      out.write("\tfont-family: 'Muli', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("/** fonts used for the icons **/ \r\n");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'FontomasCustomRegular';\r\n");
      out.write("    src: url('../fonts/fontomas-webfont.eot');\r\n");
      out.write("    src: url('../fonts/fontomas-webfont.eot?#iefix') format('embedded-opentype'),\r\n");
      out.write("         url('../fonts/fontomas-webfont.woff') format('woff'),\r\n");
      out.write("         url('../fonts/fontomas-webfont.ttf') format('truetype'),\r\n");
      out.write("         url('../fonts/fontomas-webfont.svg#FontomasCustomRegular') format('svg');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1.w3ls {\r\n");
      out.write("    font-size: 45px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    padding: 70px 0;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-family: none;\r\n");
      out.write("}\r\n");
      out.write("a.hiddenanchor{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("/** The wrapper that will contain our two forms **/\r\n");
      out.write("#wrapper{\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\tmin-height: 560px;\t\r\n");
      out.write("\tmargin:0 auto;\t\r\n");
      out.write("\twidth:35%;\r\n");
      out.write("\tposition: relative;\t\r\n");
      out.write("}\r\n");
      out.write("/**** Styling the form elements **/\r\n");
      out.write("\r\n");
      out.write("/**** general text styling ****/\r\n");
      out.write("#wrapper a{\r\n");
      out.write("\tcolor: rgb(95, 155, 198);\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper h2{\r\n");
      out.write("\tfont-size: 40px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tpadding-top:5px;\r\n");
      out.write("\tfont-weight:100;\r\n");
      out.write("\ttext-transform: capitalize;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("\tfont-family: none;\r\n");
      out.write("}\r\n");
      out.write("#wrapper h2:after{\r\n");
      out.write("\tcontent: ' ';\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 2px;\r\n");
      out.write("\tmargin-top: 25px;\r\n");
      out.write("\tbackground: -moz-linear-gradient(left, rgba(147,184,189,0) 0%,rgba(255, 255, 255, 0.8) 20%,rgb(255, 255, 255) 53%,rgba(255, 255, 255, 0.8) 79%,rgba(147,184,189,0) 100%);\r\n");
      out.write("\tbackground: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(147,184,189,0)), color-stop(20%,rgba(255, 255, 255, 0.8)), color-stop(53%,rgb(255, 255, 255)), color-stop(79%,rgba(255, 255, 255, 0.8)), color-stop(100%,rgba(147,184,189,0)));\r\n");
      out.write("\tbackground: -webkit-linear-gradient(left, rgba(147,184,189,0) 0%,rgba(255, 255, 255, 0.8) 20%,rgb(255, 255, 255) 53%,rgba(255, 255, 255, 0.8) 79%,rgba(147,184,189,0) 100%);\r\n");
      out.write("\tbackground: -o-linear-gradient(left, rgba(147,184,189,0) 0%,rgba(255, 255, 255, 0.8) 20%,rgb(255, 255, 255) 53%,rgba(255, 255, 255, 0.8) 79%,rgba(147,184,189,0) 100%);\r\n");
      out.write("\tbackground: -ms-linear-gradient(left, rgba(147,184,189,0) 0%,rgba(255, 255, 255, 0.8) 20%,rgb(255, 255, 255) 53%,rgba(255, 255, 255, 0.8) 79%,rgba(147,184,189,0) 100%);\r\n");
      out.write("\tbackground: linear-gradient(left, rgba(147,184,189,0) 0%,rgba(255, 255, 255, 0.8) 20%,rgb(255, 255, 255) 53%,rgba(255, 255, 255, 0.8) 79%,rgba(147,184,189,0) 100%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper p{\r\n");
      out.write("\tmargin-bottom:15px;\r\n");
      out.write("}\r\n");
      out.write("#wrapper p:first-child{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("#wrapper label{\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**** advanced input styling ****/\r\n");
      out.write("/* placeholder */\r\n");
      out.write("::-webkit-input-placeholder  { \r\n");
      out.write("\tcolor:#fff; \r\n");
      out.write("}\r\n");
      out.write("input:-moz-placeholder,\r\n");
      out.write("textarea:-moz-placeholder{ \r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("} \r\n");
      out.write("input {\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("label.uname span,label.youpasswd span,label.youmail span {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("/* all the input except submit and checkbox */\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]){\r\n");
      out.write("\twidth: 91%;\r\n");
      out.write("\tletter-spacing:1px;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.39);\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    padding: 10px 5px 10px 35px;\r\n");
      out.write("    border: 1px solid rgba(178, 178, 178, 0);\r\n");
      out.write("    font-family: none;\r\n");
      out.write("    -webkit-appearance: textfield;\r\n");
      out.write("    -webkit-box-sizing: content-box;\r\n");
      out.write("    -moz-box-sizing: content-box;\r\n");
      out.write("    box-sizing: content-box;\r\n");
      out.write("    -webkit-transition: all 0.2s linear;\r\n");
      out.write("    -moz-transition: all 0.2s linear;\r\n");
      out.write("    -o-transition: all 0.2s linear;\r\n");
      out.write("    transition: all 0.2s linear;\r\n");
      out.write("}\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):active,\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):focus{\r\n");
      out.write("\tborder: 1px solid rgba(91, 90, 90, 0.7);\r\n");
      out.write("\tbackground: rgba(238, 236, 240, 0.2);\t\r\n");
      out.write("\t-webkit-box-shadow: 0px 1px 4px 0px rgba(168, 168, 168, 0.9) inset;\r\n");
      out.write("\t   -moz-box-shadow: 0px 1px 4px 0px rgba(168, 168, 168, 0.9) inset;\r\n");
      out.write("\t        box-shadow: 0px 1px 4px 0px rgba(168, 168, 168, 0.9) inset;\r\n");
      out.write("} \r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):active::-webkit-input-placeholder,\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):focus::-webkit-input-placeholder  { \r\n");
      out.write("\tcolor:#fff!important; \r\n");
      out.write("}\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):active input:-moz-placeholder,#wrapper input:not([type=\"checkbox\"]):focus input:-moz-placeholder,\r\n");
      out.write("#wrapper input:not([type=\"checkbox\"]):active textarea:-moz-placeholder,#wrapper input:not([type=\"checkbox\"]):focus textarea:-moz-placeholder { \r\n");
      out.write("\tcolor:#fff!important;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/*styling both submit buttons */\r\n");
      out.write("#wrapper p.button input{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tcursor: pointer;\t\r\n");
      out.write("\tbackground:transparent;\r\n");
      out.write("\tpadding: 8px 0;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 24px;\t\r\n");
      out.write("\tborder: 2px solid #fff;\t\r\n");
      out.write("\tmargin-bottom: 10px;\t\r\n");
      out.write("\ttext-shadow: 0 1px 1px rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t-webkit-border-radius: 3px;\r\n");
      out.write("\t   -moz-border-radius: 3px;\r\n");
      out.write("\t        border-radius: 3px;\t\r\n");
      out.write("\t-webkit-transition: all 0.2s linear;\r\n");
      out.write("\t   -moz-transition: all 0.2s linear;\r\n");
      out.write("\t     -o-transition: all 0.2s linear;\r\n");
      out.write("\t        transition: all 0.2s linear;\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.button input:hover{\r\n");
      out.write("\tbackground:rgb(77, 218, 76);\r\n");
      out.write("\tborder: 2px solid rgb(77, 218, 76);\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.button input:active,\r\n");
      out.write("#wrapper p.button input:focus{\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tborder: 2px solid rgb(77, 218, 76);\t\r\n");
      out.write("\t-webkit-box-shadow: 0px 1px 6px 4px rgba(0, 0, 0, 0.2) inset;\r\n");
      out.write("\t   -moz-box-shadow: 0px 1px 6px 4px rgba(0, 0, 0, 0.2) inset;\r\n");
      out.write("\t        box-shadow: 0px 1px 6px 4px rgba(0, 0, 0, 0.2) inset;\r\n");
      out.write("}\r\n");
      out.write("p.login.button,\r\n");
      out.write("p.signin.button{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".keeplogin {\r\n");
      out.write("\tmargin-top: -5px;\r\n");
      out.write("}\r\n");
      out.write(".keeplogin input[type=\"checkbox\"] {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".keeplogin input[type=\"checkbox\"]+label {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding-left: 2em;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".keeplogin input[type=\"checkbox\"]+label span:first-child {\r\n");
      out.write("    width: 14px;\r\n");
      out.write("    height: 14px;\r\n");
      out.write("    border: 2px solid #C8C8C8;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 0;\r\n");
      out.write("\ttop: 1px;\r\n");
      out.write("}\r\n");
      out.write(".keeplogin input[type=\"checkbox\"]:checked+label span:first-child:before {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    background: url(../images/tick.png)no-repeat;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 2px;\r\n");
      out.write("    top: 2px;\r\n");
      out.write("    font-size: 10px;\r\n");
      out.write("    width: 10px;\r\n");
      out.write("    height: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.change_link{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    height: 80px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-top: 1px solid rgb(219, 229, 232);\r\n");
      out.write("    background: rgb(38, 38, 34);\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.change_link span {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 31px;\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.change_link a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("\tmargin-top:-5px;\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("    background: rgb(247, 248, 241);\r\n");
      out.write("    padding: 8px 20px;\r\n");
      out.write("    color: rgb(77, 218, 76);\r\n");
      out.write("    margin-left:185px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    -webkit-border-radius: 4px;\r\n");
      out.write("    -moz-border-radius: 4px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    border: 1px solid  rgb(77, 218, 76);\r\n");
      out.write("    -webkit-transition: all 0.4s linear;\r\n");
      out.write("    -moz-transition: all 0.4s linear;\r\n");
      out.write("    -o-transition: all 0.4s linear;\r\n");
      out.write("    -ms-transition: all 0.4s linear;\r\n");
      out.write("    transition: all 0.4s linear;\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.change_link a:hover {\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\tbackground: rgb(77, 218, 76);\r\n");
      out.write("\tborder: 1px solid  rgb(77, 218, 76);\r\n");
      out.write("}\r\n");
      out.write("#wrapper p.change_link a:active{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 1px;\r\n");
      out.write("}\r\n");
      out.write("#register, \r\n");
      out.write("#login{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\twidth: 88%;\t\r\n");
      out.write("\tpadding: 18px 6% 60px 6%;\r\n");
      out.write("\tmargin: 0 0 35px 0;\r\n");
      out.write("\tbackground:rgba(52, 53, 49, 0.58);\r\n");
      out.write("}\r\n");
      out.write("#register{\t\r\n");
      out.write("\tz-index: 21;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("}\r\n");
      out.write("#login{\r\n");
      out.write("\tz-index: 22;\r\n");
      out.write("}\r\n");
      out.write("#toregister:target ~ #wrapper #register,\r\n");
      out.write("#tologin:target ~ #wrapper #login{\r\n");
      out.write("\tz-index: 22;\r\n");
      out.write("\t-webkit-animation-delay: .6s;\r\n");
      out.write("\t-webkit-animation-timing-function: ease-in;\r\n");
      out.write("\t-moz-animation-delay: .6s;\r\n");
      out.write("\t-moz-animation-timing-function: ease-in;\r\n");
      out.write("\t-o-animation-delay: .6s;\r\n");
      out.write("\t-o-animation-timing-function: ease-in;\r\n");
      out.write("\t-ms-animation-delay: .6s;\r\n");
      out.write("\t-ms-animation-timing-function: ease-in;\r\n");
      out.write("\tanimation-delay: .6s;\r\n");
      out.write("\tanimation-timing-function: ease-in;\r\n");
      out.write("\t-webkit-animation-name: scaleIn;\r\n");
      out.write("\t-moz-animation-name: scaleIn;\r\n");
      out.write("\t-ms-animation-name: scaleIn;\r\n");
      out.write("\t-o-animation-name: scaleIn;\r\n");
      out.write("\tanimation-name: scaleIn;\r\n");
      out.write("}\r\n");
      out.write("#toregister:target ~ #wrapper #login,\r\n");
      out.write("#tologin:target ~ #wrapper #register{\r\n");
      out.write("\t-webkit-animation-timing-function: ease-out;\r\n");
      out.write("\t-moz-animation-timing-function: ease-out;\r\n");
      out.write("\t-o-animation-timing-function: ease-out;\r\n");
      out.write("\t-ms-animation-timing-function: ease-out;\r\n");
      out.write("\tanimation-timing-function: ease-out;\r\n");
      out.write("\t-webkit-animation-name: scaleOut;\r\n");
      out.write("\t-moz-animation-name: scaleOut;\r\n");
      out.write("\t-ms-animation-name: scaleOut;\r\n");
      out.write("\t-o-animation-name: scaleOut;\r\n");
      out.write("\tanimation-name: scaleOut;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** the actual animation, credit where due : http://daneden.me/animate/ ***/\r\n");
      out.write(".animate{\r\n");
      out.write("\t-webkit-animation-duration: 0.5s;\r\n");
      out.write("\t-webkit-animation-fill-mode: both;\r\n");
      out.write("\t\r\n");
      out.write("\t-moz-animation-duration: 0.5s;\r\n");
      out.write("\t-moz-animation-fill-mode: both;\r\n");
      out.write("\t\r\n");
      out.write("\t-o-animation-duration: 0.5s;\r\n");
      out.write("\t-o-animation-fill-mode: both;\r\n");
      out.write("\t\r\n");
      out.write("\t-ms-animation-duration: 0.5s;\r\n");
      out.write("\t-ms-animation-fill-mode: both;\r\n");
      out.write("\t\r\n");
      out.write("\tanimation-duration: 0.5s;\r\n");
      out.write("\tanimation-fill-mode: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** yerk some ugly IE fixes 'cause I know someone will ask \"why does it look ugly in IE?\", no matter how many warnings I will put in the article */\r\n");
      out.write("\r\n");
      out.write(".lt8 #wrapper input{\r\n");
      out.write("\tpadding: 10px 5px 10px 32px;\r\n");
      out.write("    width: 92%;\r\n");
      out.write("}\r\n");
      out.write(".lt8 #wrapper input[type=checkbox]{\r\n");
      out.write("\twidth: 10px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write(".lt8 #wrapper h2{\r\n");
      out.write("\tcolor: #066A75;\r\n");
      out.write("}\r\n");
      out.write(".lt8 #register{\t\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write(".lt8 p.change_link,\r\n");
      out.write(".ie9 p.change_link{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.agileits {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:170px 0 20px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size:16px;\r\n");
      out.write("\tfont-weight:normal;\r\n");
      out.write("}\r\n");
      out.write("p.agileits a {\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("}\r\n");
      out.write("p.agileits a:hover {\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\t\r\n");
      out.write("<h1 class=\"w3ls\"></h1>\t\t\t\r\n");
      out.write("<div id=\"container_demo\" >\r\n");
      out.write("    <a class=\"hiddenanchor\" id=\"toregister\"></a>\r\n");
      out.write("    <a class=\"hiddenanchor\" id=\"tologin\"></a>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"login\" class=\"animate form\">\r\n");
      out.write("\t\t\t<form  action=\"#\" method=\"post\" autocomplete=\"on\"> \r\n");
      out.write("                <h2>Log in</h2> \r\n");
      out.write("                <p> \r\n");
      out.write("\t\t\t\t\t<label for=\"username\" class=\"uname\"><span><i>Your email or name</i></span></label>\r\n");
      out.write("                    <input id=\"username\" name=\"username\" required=\"required\" type=\"text\" placeholder=\"Email or Username\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p> \r\n");
      out.write("                    <label for=\"password\" class=\"youpasswd\"><span><i>Your password</i></span></label>\r\n");
      out.write("                    <input id=\"password\" name=\"password\" required=\"required\" type=\"password\" placeholder=\"Password\" /> \r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"keeplogin\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"brand\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<label for=\"brand\"><span></span> Remember me?</label>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("                <p class=\"login button\"> \r\n");
      out.write("                    <input type=\"submit\" value=\"Login\" /> \r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/view/signin.jsp(14,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("resources/css/animate-custom.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/view/signin.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("resources/css/style.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }
}
